spring:
  config:
    activate:
      on-profile: aws
  cloud:
    aws:
      credentials:
#        instance-profile: true # AWS CLI에서 aws configure list 정보를 반영할건지 여부
        access-key: ${ACCESS_KEY}  # AWS IAM Access Key
        secret-key: ${SECRET_KEY}  # AWS IAM Secret Key
      s3:
        bucket: ${BUCKET} # AWS 버킷 이름
        region: ${REGION} # AWS 리전 정보
      region:
        static: ${REGION} # AWS 리전 정보
      ses:
        region: ${REGION}
        manager-email: ${MANAGER_EMAIL}
