jwt:
  secret: emstockrestapi0624emstockrestapi0624emstockrestapi0624emstockrestapi0624emstockrestapi0624emstockrestapi0624
  access-token-expiration: 1800                  # accessToken 유효시간(초) - 30분
  refresh-token-expiration: 86400                # refreshToken 유효시간(초) - 24시간

server:
  version: 1.0.0
  cors-list: ${cors-list}
  port: 10350
  encrypt-key: ${enctype-key}           # 최대32자리(256bit/32byte)

logging:
  level:
    root: info
    org.hibernate.SQL: warn

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://127.0.0.1/em_saas
    username: root
    password: Illunex123!
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false
  sql:
    init:
      schema-locations: classpath*:db/dev/schema.sql,
        classpath*:db/common/alter_table.sql
      data-locations: classpath*:db/common/code.sql
      mode: always

webhook:
  synology:
    url: ${synology-hook-url}
    api: ${synology-hook-api}
    method: ${synology-hook-method}
    version: ${synology-hook-version}
    scrap:
      token: ${synology-hook-scrap-token}
    use: true
debug:
  mode: ${debug_mode}